# Generated by Django 5.2.7 on 2026-01-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_generated_code_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestconsent',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='userconsent',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='primary_email',
            new_name='email',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='GuestConsent',
        ),
        migrations.DeleteModel(
            name='UserConsent',
        ),
    ]
