# Generated by Django 5.2.7 on 2026-01-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconsent',
            old_name='consent_text_hash',
            new_name='consent_policy',
        ),
        migrations.RemoveField(
            model_name='userconsent',
            name='consent_type',
        ),
        migrations.AddField(
            model_name='userconsent',
            name='personal_consent',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='given_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
