# Generated by Django 5.2.7 on 2026-01-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_settings', '0008_profileprivacysettings_whitelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='avatar',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='city',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='country',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='edu_level',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='first_name',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='full_desc',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='graduation_year',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='institution_name',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='last_name',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='link_to_github',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='link_to_instagram',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='link_to_telegram',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='link_to_vk',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='middle_name',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='profession',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='relocation',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='short_desc',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='wallpaper',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileprivacysettings',
            name='work_formats',
            field=models.CharField(choices=[('all', 'видно всем'), ('not_all', 'видно всем, кроме...'), ('no_one_except', 'не видно никому, кроме...'), ('nobody', 'не видно никому')], default='all', max_length=20),
        ),
    ]
