"""
Django settings for drf_blog_api project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta

import os
from pathlib import Path
from docs.utils import read_md_section
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Загрузка .env
load_dotenv('.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

if not SECRET_KEY:
    # Для разработки - генерируем каждый раз
    # Для продакшена - это вызовет ошибку (и это правильно!)
    from django.core.management.utils import get_random_secret_key
    SECRET_KEY = get_random_secret_key()
    print(f"⚠️  ВНИМАНИЕ: Используется сгенерированный SECRET_KEY: {SECRET_KEY[:20]}...")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes', 't')

if not DEBUG:
    # ПРОДАКШЕН - всегда HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # MEDIA URL с HTTPS
    MEDIA_URL = 'https://api.skillcrafts.ru/media/'
    # Или протокол-агностичный
    # MEDIA_URL = '//api.skillcrafts.ru/media/'
else:
    # РАЗРАБОТКА
    MEDIA_URL = '/media/'

# Важно: USE_X_FORWARDED_HOST и USE_X_FORWARDED_PORT
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Разрешённые хосты
allowed_hosts_str = os.getenv('ALLOWED_HOSTS', '')
if allowed_hosts_str:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',')]
else:
    # В разработке разрешаем всё, в продакшене только указанные хосты
    ALLOWED_HOSTS = ['*'] if DEBUG else [
        'portfolio-blog-api.ru',
        'www.portfolio-blog-api.ru',
        'localhost',
        '127.0.0.1',
    ]
    if not DEBUG:
        print("⚠️  ВНИМАНИЕ: ALLOWED_HOSTS не установлен для продакшена!")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_cleanup.apps.CleanupConfig',
    'mptt',
    # drf apps
    'apps.authentication', 'apps.accounts', 'apps.profiles', 'apps.consents',
    # 'apps.posts',
    'apps.privacy_settings', 'apps.media_manage',
    'apps.resume', 'apps.my_workflows', 'apps.my_knowledge',
    # django apps
    'apps.emails'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'drf_blog_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drf_blog_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Определяем, запущен ли Docker
USE_DOCKER_DB = os.getenv('USE_DOCKER_DB', 'False').lower() == 'true'

if USE_DOCKER_DB:
    # Настройки для Docker PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'drf_blog_api',
            'USER': 'drf_blog_api',
            'PASSWORD': 'drf_blog_api',
            'HOST': 'localhost',  # localhost, т.к. порт проброшен
            'PORT': '5433',
        }
    }
else:
    DATABASES = {
        # 'default': {
        #     'ENGINE': 'django.db.backends.sqlite3',
        #     'NAME': BASE_DIR / 'db.sqlite3',
        # }
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'drf_blog_api'),
            'USER': os.getenv('DB_USER', 'drf_blog_api'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'drf_blog_api'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': 300,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Статика
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # ← ОБЯЗАТЕЛЬНО!
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, 'static'),
]

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'apps.authentication.authentication.UnifiedJWTAuthentication',
        # 'rest_framework.authentication.SessionAuthentication'
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 'DEFAULT_PARSER_CLASSES': [
    #     'rest_framework.parsers.JSONParser',
    #     'rest_framework.parsers.FormParser',
    #     'rest_framework.parsers.MultiPartParser',
    # ]
}

BASE_URL = {
    'BASE_URL': 'http://127.0.0.1:8000' if DEBUG else 'https://api.skillcrafts.ru'
}

SPECTACULAR_SETTINGS = {
    # Основные настройки
    "TITLE": "API for SkillCrafts.Ru",
    "VERSION": "release version 0.1",
    "DESCRIPTION": read_md_section('api/description.md').format(**BASE_URL),

    # Включение схемы безопасности
    "SERVE_INCLUDE_SCHEMA": True,  # Оставьте True для отладки
    "SORT_OPERATION_PARAMETERS": False,

    # Важно для правильной работы с аутентификацией:
    "SECURITY": [
        {"JWTAuth": []},  # Используйте имя, которое указали в UnifiedJWTAuthenticationScheme
    ],

    # Настройки безопасности для токенов
    "SECURITY_DEFINITIONS": {
        "JWTAuth": {  # Должно совпадать с name в UnifiedJWTAuthenticationScheme
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
            "description": "JWT Bearer Token. Для пользователей и гостей."
        }
    },

    # Настройки Swagger UI
    "SWAGGER_UI_SETTINGS": {
        'deepLinking': True,  # ← Включить глубокие ссылки
        "persistAuthorization": True,  # Сохраняет авторизацию при перезагрузке
        # "displayOperationId": True,  # Показывать ID операций
        # "defaultModelsExpandDepth": 1,
        # "defaultModelExpandDepth": 1,
        "docExpansion": "list",  # или "list", "full"
        # "filter": True,
        # "showExtensions": True,
        "showCommonExtensions": True, # "displayOperationId": False,
        # "defaultModelsExpandDepth": 1,
        # "defaultModelExpandDepth": 1,
        # "defaultModelRendering": "model",
        # "displayRequestDuration": True,
        # "docExpansion": "none",
        # "filter": True,
        # "operationsSorter": "method",
        # "tagsSorter": "alpha",
        # "showExtensions": True,
        # "showCommonExtensions": True,
    },

    # Решение проблем с Enum
    # "ENUM_NAME_OVERRIDES": {
    #     "PrivacyEnum": "apps.privacy_settings.models.PRIVACIES",
    #     # Добавьте другие Enum при необходимости
    #     "LevelEnum": [
    #         "apps.resume.models.Skill.level",
    #         "apps.profiles.models.Skill.level",
    #     ],
    #     "EduLevelEnum": "apps.resume.models.Education.edu_level",
    #     "StatusEnum": "apps.resume.models.Resume.status",
    # },

    # Игнорировать проблемы с Enum
    'ENUM_RENAME_ALTERNATIVES': {
        'LevelEnum': ['SkillLevel', 'ProficiencyLevel'],
        'EduLevelEnum': ['EducationLevel'],
        'StatusEnum': ['PublicationStatus', 'ResumeStatus'],
    },

    # Подавить предупреждения
    'ENUM_ALLOW_DUPLICATE_VALUES': True,

    # Дополнительные настройки для лучшей генерации схемы
    "COMPONENT_SPLIT_REQUEST": True,
    "COMPONENT_SPLIT_PATCH": True,
    "COMPONENT_NO_READ_ONLY_REQUIRED": True,

    # Автоматическое определение URL префикса
    "SCHEMA_PATH_PREFIX": "/api/",
    "SCHEMA_PATH_PREFIX_TRIM": True,

    # Настройки для автогенерации операций
    "GENERIC_ADDITIONAL_PROPERTIES": "dict",
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
    ],

    # Исключение ненужных эндпоинтов
    # "PREPROCESSING_HOOKS": [
    #     "drf_spectacular.hooks.preprocess_exclude_path_format",
    # ],
}

# Упрощенные настройки JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=(24*60 if DEBUG else 8*60)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'AUTH_TOKEN_CLASSES': ('apps.accounts.tokens.CustomAccessToken',),
    'TOKEN_CLASSES': {
        'access': 'apps.accounts.tokens.CustomAccessToken',
        'refresh': 'apps.accounts.tokens.CustomRefreshToken',  # Укажите правильный путь
    },

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',

    # Важно для UUID
    'USER_ID_FIELD': 'id',  # Теперь это UUIDField
    'USER_ID_CLAIM': 'user_id',
    'USER_TYPE_CLAIM': 'type',

    # Для поддержки разных типов пользователей
    'TOKEN_TYPE_CLAIM': 'type',

    # Время жизни для гостей
    'GUEST_TOKEN_LIFETIME': timedelta(days=30),

    'TOKEN_OBTAIN_SERIALIZER':
        'apps.accounts.serializers.MyTokenObtainPairSerializer',
    'TOKEN_REFRESH_SERIALIZER':
        'apps.accounts.serializers.MyTokenRefreshSerializer',
    'TOKEN_VERIFY_SERIALIZER':
        'apps.accounts.serializers.MyTokenVerifySerializer',
}

# SIMPLE_JWT = {
#     'AUTH_HEADER_TYPES': ('Bearer', 'JWT'),
#     'USER_ID_FIELD': 'id',
#     'USER_ID_CLAIM': 'user_id',
# }

# CORS настройки
CORS_ALLOWED_ORIGINS = [
    "https://react-blog-kappa-plum.vercel.app",
    "https://skillcrafts.ru",
    "http://46.229.212.120",
    "https://portfolio-blog-api.ru",
    "http://localhost:5173",
    "http://localhost:4173",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:4173",
    "http://localhost:3000",  # если используете другой порт
]

# Или разрешите все origins для разработки (не для продакшена!)
# CORS_ALLOW_ALL_ORIGINS = True  # Только для разработки!

# Дополнительные настройки
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CORS_EXPOSE_HEADERS = ['Set-Cookie']

# CSRF только для админки и сессионной аутентификации
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'Lax'  # Или 'Strict'
CSRF_TRUSTED_ORIGINS = [
    "https://react-blog-kappa-plum.vercel.app",
    "https://portfolio-blog-api.ru",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Session cookies (если используете админку)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # или 'cache', 'file'
SESSION_COOKIE_AGE = 1209600  # 2 недели в секундах
SESSION_SAVE_EVERY_REQUEST = True

# SESSION_COOKIE_NAME = 'sessionid_local'
# CSRF_COOKIE_NAME = 'csrftoken_local'

# Настройки Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'postfix')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'noreply@{os.environ.get("DOMAIN", "localhost")}')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', f'admin@{os.environ.get("DOMAIN", "localhost")}')
